<?php
define('APP_PATH','/home/themarriager/public_html/tracking');
define('CLASS_PATH',APP_PATH.'/classes');
define('CAMPAIGN_CLASS_PATH',APP_PATH.'/classes/campaign');
define('TRACKER_CLASS_PATH',APP_PATH.'/classes/tracker');
define('LIB_PATH',APP_PATH.'/lib');
define('DB_USER_MYSQL','themarri_dev');
define('DB_PASSWORD_MYSQL','Them@rr1_dev');
define('DB_NAME_MYSQL','themarri_email_tracked');
define('DB_HOST_MYSQL','localhost');
define('DEFAULT_URL','http://www.themarriager.com/tracking/');
?>